version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install-and-test:
    executor:
      name: node/default
      tag: "16.17"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
          name: Run tests
  deploy:
    executor:
      name: node/default
      tag: "16.17"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build << pipeline.git.branch >>
          command: npx react-scripts build

workflows:
  test_and_deploy_my_app:
    jobs:
      - install-and-test
      - deploy
